CREATE PROCEDURE FI_SP_BeneficiarioExistePorCpf
    @IDCLIENTE BIGINT,
    @CPF VARCHAR(11)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 1
    FROM BENEFICIARIOS
    WHERE IDCLIENTE = @IDCLIENTE
      AND CPF = @CPF
END
